package com.datastax.oss.driver.internal.core.metadata.token;

import net.jcip.annotations.Immutable;

/** A token generated by {@code CDCPartitioner}. */
@Immutable
public class CDCToken extends TokenLong64 {

  public CDCToken(long value) {
    super(value);
  }

  @Override
  public String toString() {
    return "CDCToken(" + value + ")";
  }
}
